import img1 from "../assets/movie/img1.jpg";
import img2 from "../assets/movie/img2.webp";
import img3 from "../assets/movie/img3.webp";
import img4 from "../assets/movie/img4.webp";
import img5 from "../assets/movie/img5.webp";
import img6 from "../assets/movie/img6.webp";
import img7 from "../assets/movie/img7.webp";

export default function getMovies() {
  return [
    {
      id: "1", 
      title: "House of the Dragon", 
      description: "The story of the Targaryen civil war.",
      img: img1,
      year: "2022",
      maturityRating: "TV-MA",
      duration: "50m",
      imdbRating: "8.4",
      userReviewCount: "1.2K",
      criticReviewCount: "145",
      popularity: "12",
      genres: ["Action", "Adventure", "Drama"],
      trailerDuration: "2:45",
      videoCount: 24,
      photoCount: 156,
      director: ["Clare Kilner", "Geeta Vasant Patel"],
      writers: ["George R.R. Martin", "Ryan Condal"],
      stars: ["Matt Smith", "Emma D'Arcy", "Olivia Cooke"]
    },
    {
      id: "2", 
      title: "Game of Thrones", 
      description: "Nine noble families fight for control over the mythical lands of Westeros.",
      img: img2,
      year: "2011",
      maturityRating: "TV-MA",
      duration: "57m",
      imdbRating: "9.2",
      userReviewCount: "5.4K",
      criticReviewCount: "482",
      popularity: "2",
      genres: ["Action", "Adventure", "Drama"],
      trailerDuration: "2:15",
      videoCount: 42,
      photoCount: 850,
      director: ["David Nutter", "Alan Taylor"],
      writers: ["David Benioff", "D.B. Weiss", "George R.R. Martin"],
      stars: ["Emilia Clarke", "Kit Harington", "Peter Dinklage"]
    },
    {
      id: "3", 
      title: "A Knight of the Seven Kingdoms", 
      description: "The adventures of Ser Duncan the Tall and Egg.",
      img: img3,
      year: "2025",
      maturityRating: "TV-14",
      duration: "1h 00m",
      imdbRating: "7.8",
      userReviewCount: "120",
      criticReviewCount: "34",
      popularity: "88",
      genres: ["Adventure", "Drama", "Fantasy"],
      trailerDuration: "1:50",
      videoCount: 5,
      photoCount: 28,
      director: ["Owen Harris"],
      writers: ["George R.R. Martin", "Ira Parker"],
      stars: ["Peter Claffey", "Dexter Sol Ansell"]
    },
    {
      id: "4",
      title: "The Lord of the Rings: The Rings of Power",
      description: "A prequel to the events of The Lord of the Rings, set in the Second Age of Middle-earth.",
      img: img4,
      year: "2022",
      maturityRating: "TV-14",
      duration: "1h 10m",
      imdbRating: "7.0",
      userReviewCount: "3.1K",
      criticReviewCount: "210",
      popularity: "15",
      genres: ["Action", "Adventure", "Drama"],
      trailerDuration: "2:30",
      videoCount: 18,
      photoCount: 320,
      director: ["J.A. Bayona", "Wayne Che Yip"],
      writers: ["J.R.R. Tolkien", "Patrick McKay", "John D. Payne"],
      stars: ["Morfydd Clark", "Ismael Cruz Cordova", "Charlie Vickers"]
    },
    {
      id: "5",
      title: "The Witcher",
      description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
      img: img5,
      year: "2019",
      maturityRating: "TV-MA",
      duration: "1h 00m",
      imdbRating: "8.0",
      userReviewCount: "2.8K",
      criticReviewCount: "190",
      popularity: "45",
      genres: ["Action", "Adventure", "Drama"],
      trailerDuration: "2:10",
      videoCount: 15,
      photoCount: 240,
      director: ["Alik Sakharov", "Charlotte Brändström"],
      writers: ["Andrzej Sapkowski", "Lauren Schmidt Hissrich"],
      stars: ["Henry Cavill", "Anya Chalotra", "Freya Allan"]
    },
    {
      id: "6",
      title: "Stranger Things",
      description: "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
      img: img6,
      year: "2016",
      maturityRating: "TV-14",
      duration: "51m",
      imdbRating: "8.7",
      userReviewCount: "4.9K",
      criticReviewCount: "350",
      popularity: "8",
      genres: ["Drama", "Fantasy", "Horror"],
      trailerDuration: "2:55",
      videoCount: 38,
      photoCount: 610,
      director: ["The Duffer Brothers"],
      writers: ["Matt Duffer", "Ross Duffer"],
      stars: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"]
    },
    {
      id: "7",
      title: "The Mandalorian",
      description: "A lone gunfighter makes his way through the outer reaches of the galaxy, far from the authority of the New Republic.",
      img: img7,
      year: "2019",
      maturityRating: "TV-14",
      duration: "40m",
      imdbRating: "8.6",
      userReviewCount: "2.1K",
      criticReviewCount: "185",
      popularity: "22",
      genres: ["Action", "Adventure", "Sci-Fi"],
      trailerDuration: "2:02",
      videoCount: 22,
      photoCount: 430,
      director: ["Dave Filoni", "Jon Favreau"],
      writers: ["Jon Favreau", "George Lucas"],
      stars: ["Pedro Pascal", "Katee Sackhoff", "Carl Weathers"]
    }
  ];
}
